### ISSUE TITLE
reconsider moving online

### ISSUE THREAD

**Issue by wikfeldt** [nordic-rse/nordic-rse.github.io#103]
i'm not convinced that we should completely dismiss the idea of making NordicRSE2020 an online event. I would not want it to be just a series talks and possibly using regular zoom breakout rooms for some discussion sessions, as in CR workshops. But if we could make it more innovative I think it could be worth considering. People are building great tools for more interactive remote events and if we would use them well it could give a great experience for everyone. 
For example:
- https://theonline.town/overview (for mingling between sessions)
- https://qiqochat.com/about, https://youtu.be/HUyTOBfRlw0 (a "wrapper" around zoom, could be used for the conference)

**Comment by bast** [comment]
I agree, we should discuss this option.

**Comment by annefou** [comment]
agreed to move Nordic-RSE f2f to May 2021 and replace Nordic-RSE2020 to online event "Nordic-RSE Get-together"

**Comment by annefou** [comment]
I will work on updating the website.

**Comment by rantahar** [comment]
Should this be closed?

**Comment by wikfeldt** [comment]
yes, closing
