### ISSUE TITLE
announcement email template

### ISSUE THREAD

**Issue by wikfeldt** [nordic-rse/nordic-rse.github.io#123]
Welcome to the [first online get-together event of the Nordic Research Software Engineer initiative](https://nordic-rse.org/events/2020-online-get-together/) on Nov 30 to Dec 2! 

Are you employed to develop software for research? Or are you simply spending more time developing software than conducting research? Then you have much in common with a growing international network of research software engineers, RSEs. The Nordic-RSE initiative aims to build a community of RSEs in the Nordics, plan meetings and workshops where knowledge can be shared, organize a biannual conference, and provide assistance in starting local RSE groups or hiring RSE staff in Nordic universities. 

This online event will start with two invited talks on November 30 to set the stage, and will be followed by free-form conversations, short talks, workshops, or other types of contributions on December 1-2. Do you have an idea for a technical talk or short workshop that might not fit into a conference in your academic domain but might appeal to other technical people? Please consider submitting a lightweight abstract! If you're unsure whether your idea fits the scope, you can [get in touch](mailto:contact@nordic-rse.org) to discuss it or browse the programme of the last [UK-RSE conference in 2019](https://rseconuk2019.sched.com/) to see the list of RSE topics discussed there. You can of course also register without presenting! 

More details, a registration form and information abstract submission can be found on the event page: https://nordic-rse.org/events/2020-online-get-together/
Join us for the first Nordic-RSE get-together to develop your skills, meet like-minded people, learn about new job opportunities or find people to hire, and join an advocacy network for better research!

**Comment by bast** [comment]
Should we refer to the 2019 international RSE conference?

**Comment by bast** [comment]
Instead of "that most of your academic colleagues might not find interesting but might appeal to other technical people" I suggest "that might not fit into a conference in your academic domain but ..."

**Comment by wikfeldt** [comment]
> Should we refer to the 2019 international RSE conference?

yeah probably, I linked to 2018 version because I thought that was framed as the international conference while 2019 was the UK version (RSEConUK-2019). But even if that's the case it's probably better to link to 2019

**Comment by wikfeldt** [comment]
> Instead of "that most of your academic colleagues might not find interesting but might appeal to other technical people" I suggest "that might not fit into a conference in your academic domain but ..."

thanks, I updated the original comment

**Comment by rkdarst** [comment]
From meeting yesterday, I was thinking about how to target things:

Need: you are a researcher but seem different than others and don't fit.  (already there, should we more directly emphasize the don't fit part as the "hook"?)

We provide: networking among like-minded people.  Career development (skill development, advocacy).  Join advocacy network for better research.  Provide assistance on finding jobs.  If you need to hire these people, we can help too.

I don't think this necessarily needs to be added, I am sort of thinking via writing here trying to find my preferred hooks for people.

**Comment by naoe-tatara** [comment]
Thank you, @wikfeldt  for the excellent draft! Just one comment from my end: The first sentence in the third paragraph, "This online event will start with two invited talks on November 30 to set the stage, and will be followed by free-form conversations and contributed short talks and workshops during two morning sessions on December 1-2. " sounds like (or I feel like it implies) that the program ends before noon. Maybe it is only me, but how about simply removing "during two morning sessions", and possibly edit "free-form conversations and contributed short talks and workshops" to "free-form conversations, short talks, workshops, or other types of contributions"?

**Comment by wikfeldt** [comment]
thanks @naoe-tatara and @rkdarst ! i've implemented your changes

**Comment by bast** [comment]
I reused most of the above for the PDC newsletter (pre-copy-editing):
```
Title: First online get-together event of the Nordic Research Software Engineer
initiative

Please join the first online get-together event of the Nordic Research Software
Engineer initiative on Nov 30 to Dec 2:
https://nordic-rse.org/events/2020-online-get-together/

Are you employed to develop software for research? Or are you simply spending
more time developing software than conducting research? Then you have much in
common with a growing international network of research software engineers,
RSEs. The Nordic-RSE initiative aims to build a community of RSEs in the
Nordics, plan meetings and workshops where knowledge can be shared, organize a
conference biannually, and provide assistance in starting local RSE groups or
hiring RSE staff in Nordic universities.

This online event will start with two invited talks on November 30 to set the
stage, and will be followed by free-form conversations, short talks, workshops,
or other types of contributions on December 1-2. Do you have an idea for a
technical talk or short workshop that might not fit into a conference in your
academic domain but might appeal to other technical people? Please consider
submitting a lightweight abstract! If you're unsure whether your idea fits the
scope, you can get in touch (contact@nordic-rse.org) to discuss it or browse
the programme of the last UK-RSE conference in 2019
(https://rseconuk2019.sched.com/) to see the list of RSE topics discussed
there. You can of course also register without presenting!

More details, a registration form and information abstract submission can be
found on the event page: https://nordic-rse.org/events/2020-online-get-together/

Join us for the first
Nordic-RSE get-together to develop your skills, meet like-minded people, learn
about new job opportunities or find people to hire, and join an advocacy
network for better research!
```

**Comment by bast** [comment]
Correction that I got:
> organize a conference biannually -> organize a biannual conference

Applying to both texts above.

**Comment by rantahar** [comment]
I'm guessing this should be closed? Feel free to open it if you disagree :)
