### ISSUE TITLE
We need to update the image on the get-together page

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#137]
Right now it says speaker is "CodeRefinery" and image is the logo. @rkdarst

**Comment by rkdarst** [comment]
@eglerean, can you help us to update the image?

Instead of CodeRefinery as keynote speaker, add me.

Although it's not technically correct that I was "invited"...

**Comment by bast** [comment]
I can also help with that if you can tell me where to find the sources.

**Comment by bast** [comment]
It's also OK to keep the CR logo as picture but the talk is not so much about CR.

**Comment by eglerean** [comment]
did you find the image? I put a copy here: https://github.com/nordic-rse/nordic-rse-materials

Sorry I am not able to help in these days with nordic-rse.

**Comment by bast** [comment]
Richard, I can probably fix the card. What image would you like to have there in place of the CR logo?

**Comment by bast** [comment]
@samumantha fixed it. Thanks!
