### ISSUE TITLE
get-together: Separate abstract page

### ISSUE THREAD

**Issue by naoe-tatara** [nordic-rse/nordic-rse.github.io#141]
@rkdarst  will work on it?

**Comment by rkdarst** [comment]
Does anyone have preferences between:

- a jekyll layout page + page metadata for each event

- No special layout, explicit markdown for each event.

(a) makes it easy to customize in the short term, but much harder to
move away from jekyll in the long term.  I was originally thinking (a)
but now for long-term maintenance I am thinking (b).

**Comment by bast** [comment]
I was also thinking between:
- all schedule, including abstracts is in one yaml metadata block and websites are generated from it
- everything is just markdown/html

I don't think metadata hinders migrating away since we can easily convert it to another format.

**Comment by rkdarst** [comment]
How would everything be done with one yaml file, generating different
pages?  Unfortunately that goes beyond my jekyll skills, but I started
already a simple "separate md->html page for each event" already.

**Comment by bast** [comment]
Let's go for low-tech. Maybe what I was suggesting is not easy/possible.

**Comment by bast** [comment]
Done in f51e5db1a55a648d0ecbe7be2e5bb3acd10f3741.
