### ISSUE TITLE
Two pull requests got closed by me changing default branch

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#146]
- https://github.com/nordic-rse/nordic-rse.github.io/pull/118
- https://github.com/nordic-rse/nordic-rse.github.io/pull/111

I cannot reopen them. So let's not lose them.

**Comment by rantahar** [comment]
Recreated #111, with some modifications. @rkdarst has a better version of #118.

**Comment by bast** [comment]
Thanks! One is already in, the other one is followed-up in #151.
