### ISSUE TITLE
We need some structure to be able to upload/share slides.

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#169]

**Comment by wleoncio** [comment]
I have a couple of those at my workplace. One private repo for internal slides and a public one for public slides. Then people are free to upload slides on whatever format they want (I always do Markdown so they get neatly rendered).

**Comment by bast** [comment]
Alternative (thanks for suggestion from Jeremy): give presenters the option to self-host on Zenodo, Figshare, ... and provide us with a DOI.

**Comment by wleoncio** [comment]
Sounds like a solution that works for both presenters and organizers. :+1:

**Comment by jcohen02** [comment]
So we would provide a couple of options?
 - Provide a version of your slides in PDF format that we can upload and link to from the agenda on the event website
 - Self-archive your slides/presentation materials on a site such as Zenodo, Figshare, Slideshare, etc and provide a link/DOI that we can add to the agenda

**Comment by bast** [comment]
All we can do is to encourage slides with DOI/PID?
