### ISSUE TITLE
remove unused mailing list to coderefinery zulip

### ISSUE THREAD

**Issue by annefou** [nordic-rse/nordic-rse.github.io#17]
with a nordic-rse topic

**Comment by annefou** [comment]
And unused slack channel (uk channel). Better to have one single place with coderefinery zulip.

**Comment by bast** [comment]
The problem withe the Slack channel is that messages disappear after a while. On Zulip they remain and it could be beneficial both for RSE and for CodeRefinery members to know about the other organization.

**Comment by konstantinstadler** [comment]
On the other side - we have a pretty much used RSE - NTNU channel on the UK-RSE which keeps everything in one place. AFAK zulip has the same 10k message restriction unless you pay or host yourself. Is coderef running its own instance?

**Comment by bast** [comment]
We were fortunate to get this https://zulipchat.com/for/open-source/. So there is no limit.

**Comment by annefou** [comment]
https://coderefinery.zulipchat.com/#narrow/stream/213720-nordic-rse

**Comment by bast** [comment]
We discussed this today via video and concluded that we will discuss on Zulip until we find a better place but I will also soon open a mailing list for announcements only for those who want to stay informed but do not want to sign up to yet another chat.
