### ISSUE TITLE
Add session chair persons

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#175]
- Jarno chairs day 1
- Naoe chairs lightning talks
- Emiliano chairs Tuesday 10:30 session
- Naoe chairs Wednesday 10:30 session

Is this correct @rantahar @naoe-tatara @emolinaro?

**Comment by emolinaro** [comment]
I confirm.

**Comment by naoe-tatara** [comment]
I do, too :)

**Comment by rantahar** [comment]
Correct :+1:

**Comment by bast** [comment]
Thanks all! I will now work on putting this on the web.
