### ISSUE TITLE
Should we move nordic rse github repository to CodeRefinery?

### ISSUE THREAD

**Issue by annefou** [nordic-rse/nordic-rse.github.io#18]

**Comment by bast** [comment]
I thought more about it. If the Nordic RSE becomes a "thing" which I hope it will, then it might be good if it has its own organization to collect repositories, projects, and issues.

The advantage of having it below https://github.com/coderefinery would be that issues are more visible to CodeRefinery staff and less likely to get forgotten. But in the long term a separate organization might be better?

**Comment by konstantinstadler** [comment]
I would opt for a separate repository (following the reasoning of the first paragraph by @bast) . However,  could it be hosted on the gitlab instance of coderefinery?

**Comment by bast** [comment]
We could also host in on GitLab and serve the website as GitLab pages from there. What do others think?

**Comment by bast** [comment]
Closing this issue, at least for the moment. Now that we are planning the conference this organization and repository to me seems like a good place without creating friction for others. But happy to reopen this later.
