### ISSUE TITLE
Abstracts: simple links are not clickable

### ISSUE THREAD

**Issue by wleoncio** [nordic-rse/nordic-rse.github.io#186]
# Issue 

Some of the links inside the expandable abstracts on https://nordic-rse.org/events/2020-online-get-together/ are not clickable. Neither are the specific pages for each session. Specifically, this seems to affect any posted URL which was not formatted as `[]()`.

# Examples

- https://nordic-rse.org/events/2020-online-get-together/eosc/
- https://nordic-rse.org/events/2020-online-get-together/oslo-centre-for-biostatics-epidemiology/

**Comment by wleoncio** [comment]
I guess one workaround would be to rewrite the affected links as `[URL](URL)`, but maybe there's a solution that fixes everything on the website at once.

**Comment by rkdarst** [comment]
In commonmark (or some versions of markdown), links aren't clickable
by default.  Tag them with `<>` to make them, for example
`<https://nordic-rse.org>`.  I think this is the "official" solution,
though it remains to be seen if there is some bug with zola + markdown
+ this solution.  Are the links clickable in other places?

**Comment by bast** [comment]
Confirming that `<url>` instead of `url` should solve this.

**Comment by wleoncio** [comment]
I'm in favor of observing CommonMark. So I guess I'll fix mine and just mark this as solved. Maybe also tag it as "wontfix" for better referencing.

**Comment by bast** [comment]
I think we can relatively easily fix all of them. Should I do that?

**Comment by wleoncio** [comment]
I still stand by my previous comment, but a universal solution will definitely make the website more consistent.

**Comment by bast** [comment]
Will you send the pull request for your change? I can then do the rest.

**Comment by wleoncio** [comment]
Sorry, @bast, I somehow managed to commit to the new branch and forgot to open the PR for the merge. 😅  Thanks for the reminder!
