### ISSUE TITLE
RSE conference 2020

### ISSUE THREAD

**Issue by annefou** [nordic-rse/nordic-rse.github.io#20]
- It should be announced on the website even if the date is not defined yet.
- Should we write a blog on it? Tweets?

**Comment by konstantinstadler** [comment]
Not sure how much has been decided yet... but do we have a approximate date? Also, I would first wait for some kind of conference webpage to be linked to (especially for tweets)

**Comment by bast** [comment]
We are looking for dates and location. I know we should fix it soon. Suggestions welcome :-)

**Comment by bast** [comment]
For the dates we are targeting October 14-15, 2020. Location still to be decided. We will very soon start an open call for venues.
