### ISSUE TITLE
Add a calendar with community events, workshops and meetings

### ISSUE THREAD

**Issue by rantahar** [nordic-rse/nordic-rse.github.io#215]

**Comment by PatricHolmvall** [comment]
In lack of better suggestions, a Google calendar will be used as a first trial. There are essentially two ways we can set up an easy-to-share Google calendar:

1. Create it with a personal account, manually invite administrators, and set the "Access Permission" to "Public".
2. Create a Google group calendar. It seems that this can only be set up/administrated via an organization account on "Google for business". It is possible to create a non-profit organization, but it seems like someone might have already set this up for Nordic-RSE in the past.

While we figure out if there is already a Nordic-RSE group/organization, I have set up a simple calendar and started inviting some of the Nordic-RSE members. If you want to be invited as an administrator, please contact me.

**Comment by PatricHolmvall** [comment]
To create a Google non-profit organization, we need to register the organization. This in turn requires that we sort out the statutes etcetera.

We have created a public google-calendar with our private google accounts, which can be used for now. See the [biweekly meeting HackMD](https://hackmd.io/@nordic-rse/biweekly#2021-05-12), or the discussion on Zulip.

**Comment by PatricHolmvall** [comment]
Closing the issue: we will use the [public google-calendar](https://calendar.google.com/calendar/u/0?cid=OGxpNmhqY2ptOTVnNzZwZ3RlMXA1cGkwNWNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ) for now. This calendar has been added to e.g. the website. For admin access, contact Patric or Radovan.
