### ISSUE TITLE
Add list of Research Software Journals to website

### ISSUE THREAD

**Issue by samumantha** [nordic-rse/nordic-rse.github.io#254]
In the unconference discussion about research software journals we came up with the idea that it would be great to have a list of research software journals and possibly experiences and some other interesting points (eg ranking in different countries) 

There could also be some hints about how to put code on zenodo etc.

What do you think?
Where would be a good place?

**Comment by lucaferranti** [comment]
maybe there could be a "resources" section collecting useful resources?

**Comment by samumantha** [comment]
Then a list of interesting courses/material teaching about RSE related stuff could also be there?
- eg CodeRefinery, stuff like this: https://www.software.ac.uk/blog/2021-06-16-guis-research-software-why-are-they-relevant-part-one (I visited the course last week and found it very helpful as a starting point), etc
...which made me think if it should be resources only from Nordics?
