### ISSUE TITLE
Landing page redesign

### ISSUE THREAD

**Issue by samumantha** [nordic-rse/nordic-rse.github.io#270]
Landing page with very limited information for good overview

* One panel with grid like structure similar to 'what we do'  section here : https://society-rse.org/ containing
  * events
  * what we do
  * what can we do for you
  * what you can do for us

* Twitter feed on the side (as it is now)

* bottom panel with some news (please @lucaferranti and @annefou specify what you decided in meeting in comments below)

Screenshot from planning in whimsical (let @samumantha know if you want access):
![image](https://user-images.githubusercontent.com/32324155/129044588-f1a9aebf-1eb0-44a9-80b2-a27fb60182c2.png)

**Comment by lucaferranti** [comment]
For the what we do box (which is what I and Anne discussed today) I meant something like this:

![image](https://user-images.githubusercontent.com/49938764/129061678-270a7ecc-b7ea-4d4e-8228-21ec418c070a.png)

**Comment by lucaferranti** [comment]
The above screenshot is plain html+css, so I presume it's not too much work to get it in the webpage, but I need to gain more acquaintance with zola

**Comment by lucaferranti** [comment]
![image](https://user-images.githubusercontent.com/49938764/129063953-f742eca2-ead4-4cf3-b3dc-5134e8b52ccb.png)

**Comment by lucaferranti** [comment]
![image](https://user-images.githubusercontent.com/49938764/129067923-91a696df-b703-4992-9403-59aab48dde07.png)

something like this? Then on the left of the twitter bar we could have only a news session and a few important things we want to highlight. Currently the home page has a lot of info, that could be delegated to specialized pages if they are easier to find after the updated navbar and landing page

**Comment by bast** [comment]
I really like the new landing page design. I don't think there needs to be more.

**Comment by lucaferranti** [comment]
is it ok if I open a PR with the html code for that? I think everyone can push to that branch then (to change content, layout etc)?

**Comment by bast** [comment]
Yes, can you please share somewhere the CSS for this? Can be a draft PR. It would be wonderful to get this in before Thursday.
