### ISSUE TITLE
The map disappeared from the navigation after redesign

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#283]

**Comment by lucaferranti** [comment]
I think it would be nicer if the map were in the members page, at the moment there is a link with a separate page with the map. Is this "embedding of the map" doable or is it tricky?

**Comment by bast** [comment]
It's doable. So should we move the map and its data under this repo and disband the other repo? Only disadvantage is that we would lose history of contributions if somebody later complains "why am I on this map? who added me?" - but maybe that's unlikely?

Or we can keep the data in the other repo and only move the web app to here.

**Comment by lucaferranti** [comment]
if keeping the data in the other repo and move only the web app here is doable without too many difficulties, then I would suggest to go that way.

**Comment by rkdarst** [comment]
I've always thought that map (at least the data yaml itself) in a
separate repo is a good idea, since it contains data on individual
people, and it is probably best to carefully keep that from general
website data.
