### ISSUE TITLE
Picture on landing page?

### ISSUE THREAD

**Issue by samumantha** [nordic-rse/nordic-rse.github.io#296]
For now could be for example this: https://github.com/nordic-rse/nordic-rse-materials/blob/main/graphics/www/NordicRSE_TwitterCard.png

Suggestions for other graphics welcome, happy to create more :)

Could be above the purple box?

**Comment by lucaferranti** [comment]
would also pretty cool to have a rotating gallery like in society-rse, don't think it can be achieved in pure html/css though 🤔

**Comment by bast** [comment]
I mean no problem to add more JS if CSS is not enough.

**Comment by samumantha** [comment]
Feel free to do that, my website skillz end with adding the picture ;)
