### ISSUE TITLE
Shorten text on landing page

### ISSUE THREAD

**Issue by samumantha** [nordic-rse/nordic-rse.github.io#297]
Suggestion to still shorten the text on the landing page. 
All should probably somewhere, but not all has to be on the landing page, does it?

In whimsical we had news under the box, but I believe we decided against it. Do not remember what we decided to have there though, anyone remember?

**Comment by lucaferranti** [comment]
@samumantha can this be closed?

**Comment by samumantha** [comment]
If you are happy with the way it is now? 
Maybe it can be closed and a new opened to make the text that is there now nicer?

**Comment by lucaferranti** [comment]
I think the current homepage looks very good. Focused with some catching information and visual links (road map purple box) to go to the right places for more details!

**Comment by samumantha** [comment]
Then let's close it and if someone wants to edit it more there can be a new issue
