### ISSUE TITLE
How to become a sponsor missing

### ISSUE THREAD

**Issue by lucaferranti** [nordic-rse/nordic-rse.github.io#298]
The webpage purple box link "how to become a sponsor" currently points to a placeholder page

**Comment by samumantha** [comment]
Do we have a way for this already? Or will this be something the board figures out at some point?

**Comment by lucaferranti** [comment]
I think this hasn't been discussed much at board level yet

**Comment by lucaferranti** [comment]
decision from 2022-02-03 meeting, the "become a sponsor" in the purple box is to be replaced with a "Join us \\ learn the benefits of joining Nordic-RSE" text

**Comment by bast** [comment]
This looks like already implemented. Closing
