### ISSUE TITLE
Seminar report: Rust & Python

### ISSUE THREAD

**Issue by samumantha** [nordic-rse/nordic-rse.github.io#303]
A short report a la https://nordic-rse.org/blog/seminar-report-julia-package/ ?

**Comment by bast** [comment]
Good idea. This would also be a good excuse for me to put few important points into writing which I just jumped over.

**Comment by samumantha** [comment]
Let me know if I can help somehow :)

**Comment by bast** [comment]
I doubt this will happen. Sorry :-)
