### ISSUE TITLE
Join us page

### ISSUE THREAD

**Issue by samumantha** [nordic-rse/nordic-rse.github.io#306]
Should there be an in-between page before linking to the sign up formular?

Something that is on current landingpage  (like https://nordic-rse.org/#who-we-are) maybe?

**Comment by bast** [comment]
Yes. Redirecting directly to the sign-up form is a bit harsh. It was just made to avoid to link to nowhere.

**Comment by samumantha** [comment]
To be done: adjust text to fit together with future new landing page text

**Comment by samumantha** [comment]
Maybe done enough for now...
