### ISSUE TITLE
past events and calendar pointing nowhere

### ISSUE THREAD

**Issue by lucaferranti** [nordic-rse/nordic-rse.github.io#314]
It seem that past events and calendar disappeared from the [events page](https://nordic-rse.org/events/), but the past events and calendar links in the navbar are still pointing to that page

**Comment by samumantha** [comment]
Oh no. Sorry that was me. I thought I moved everything and adjusted links. Will look for them later today. Sorry :(

**Comment by samumantha** [comment]
Hah, ok yes, I forgot to update base. Sending fixing PR in a second
