### ISSUE TITLE
link to survey result analysis

### ISSUE THREAD

**Issue by wikfeldt** [nordic-rse/nordic-rse.github.io#35]
https://github.com/nordic-rse/RSE_intro_survey/blob/master/analysis/results_nordics_2018_narrative.ipynb

**Comment by rlonka** [comment]
These issue can be closed now, right?

**Comment by wikfeldt** [comment]
i was thinking that we could add a paragraph about the survey and add a link to the results to nordic-rse.org. That's not there yet right?

**Comment by rlonka** [comment]
Right. What would be best place to add it to?  Maybe we can have Events section?

**Comment by wikfeldt** [comment]
what about adding a short section just below https://nordic-rse.org/#are-you-a-research-software-engineer where we introduce and summarize the survey results?

**Comment by rlonka** [comment]
Yes,  sounds good to me.
