### ISSUE TITLE
Generate list on local communities based on map

### ISSUE THREAD

**Issue by frankier** [nordic-rse/nordic-rse.github.io#367]
The suggestion was that we could have e.g.

 * Finland
   * Aalto University (8)
   * University of Jyväskylä (3)
 * Norway
   * Tromso University (3)

Then there are links to individual pages with lists of people.

**Comment by frankier** [comment]
I can try to tackle this.

**Comment by rantahar** [comment]
I guess nothing came out of this? There is a Finnish local community, so we should create a page for it.

**Comment by rantahar** [comment]
Actually, closing since there is a later issue with a bit more planning
