### ISSUE TITLE
Make us look more active

### ISSUE THREAD

**Issue by rantahar** [nordic-rse/nordic-rse.github.io#372]
When seeing the page for the first time, a visitor might wonder if we are still active or if the page is old. We should highlight ongoing activities a bit more.

- Events page should list
    - coffee breaks
    - community meetings
 
- Make "Get Involved: Learn how you can help us" sound less like work. Maybe "How to get in touch". It links to a page about Zulip, community meetings and so on.

- Remove the link to the timeline. It's not up to date.

- Maybe add news sections? This would need to be kept up to date.

**Comment by rantahar** [comment]
I guess the blog is kind of like the news section. But we don't have anything there from the spring...

**Comment by lucaferranti** [comment]
- "how to join" --> "become a member"

**Comment by mtomasini** [comment]
Another thing that made me wonder about how active the network was, is the map (/communities/map), with only a few people scattered around the Nordics. I realize that not everyone wants their name on the map, but then maybe it could be more useful to start the page by writing how many members there are in the network and where (more or less), how many groups, and only at the end of the page having the map?

**Comment by rantahar** [comment]
I wonder what numbers we would use here. The mailing list (unofficial members) has 74 members. We have 4 official members, but this is not advertised yet. The Nordic RSE Zulip stream has 249 members.

**Comment by rantahar** [comment]
The best way would be to combine the current "local communities" page with the "map" page. I will suggest this in my PR

**Comment by rantahar** [comment]
@mtomasini, can you take a look at the PR? I cannot add you as a reviewer, since you are not a team member. Would you like to be?

**Comment by mtomasini** [comment]
> @mtomasini, can you take a look at the PR? I cannot add you as a reviewer, since you are not a team member. Would you like to be?

Hey, if you think it would be useful, I would be totally down for it. And I just submitted my review in the PR, but just by eyeballing the code, I didn't have time to fork and build locally.

**Comment by rantahar** [comment]
This is an old issue, but actually still relevant. It would be nice to get the blog post PR merged. The news will be updated in the unconference PR.

We will get more blog posts from the unconreference, but it would be a good idea to push this a bit more.

But mainly, someone needs to periodically take a look and update the front page.

**Comment by mtomasini** [comment]
In general, coming up with more blog posts (from different members), even short ones, would make us look active!
