### ISSUE TITLE
Formatting of unconference schedule

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#392]
> for the schedule, I suggest to use the `<summary>` and `<details>` tag, so that one can expand the abstract if they want

> inspiration: https://juliareach.github.io/juliareach-days-3/#program

**Comment by lucaferranti** [comment]
can take, since I had written the original html in the other webpage. I'll just copy and adapt

**Comment by lucaferranti** [comment]
fixed in #395
