### ISSUE TITLE
Remove Community section and keep map

### ISSUE THREAD

**Issue by rlonka** [nordic-rse/nordic-rse.github.io#41]
I would like to suggest to remove community site and keep Map only. These are redundant informations and Map ha nicer interface.  
Maybe we could rename it to Community Map or something?

**Comment by bast** [comment]
I like the suggestion "Community map". My motivation for preferring the map is that I can use it in presentations and meetings. Much nicer to put a map on a slide than put a (hopefully) long list on a slide.

**Comment by bast** [comment]
I reworked it a bit but kept the page since it can still be useful to have a list of groups, in addition to the map but I would not mind if the map takes over one day.
