### ISSUE TITLE
Suggestions for main page

### ISSUE THREAD

**Issue by bast** [nordic-rse/nordic-rse.github.io#59]
- too much text still
- make first paragraphs and "what is RSE" sound less formal/academic
- what do we do?
- also make it for those who are post-docs and phds and do some RSE work but hesitate to call themselves "RSEs"
- goal of front page: make people follow our activities

**Comment by rkdarst** [comment]
Except for not being short enough, I think most of these are done now - at least enough for a first iteration.

**Comment by bast** [comment]
Thanks!
