### ISSUE TITLE
On website, bullet points have larger font size than paragraphs

### ISSUE THREAD

**Issue by rkdarst** [nordic-rse/nordic-rse.github.io#68]
At least on my computer with different javascript blocked, the font size of the paragraph elements is smaller than the bullet points.

I think this is the case on one of other websites, too.

**Comment by bast** [comment]
I am not sure I see it. I tried also with JS off. Can you attach a screenshot? Which browser?

**Comment by rkdarst** [comment]
![image](https://user-images.githubusercontent.com/6877977/87859665-89c91200-c93f-11ea-9e34-9358bf91b958.png)

It happens on one of my computers but not the other, so I guess it's probably just me and this shouldn't be pursued.  Both of these are firefox, a fairly modern version (latest or second latest version, for example 78 on the computer with that screenshot)  My guess is that the sizes are set by different CSS/javascript mechanisms, and since I block javascript by default somehow stuff going wrong.  But, that doesn't explain why it works on one but not the others, since I similarly block on both of them... and the problem doesn't change as I block/unblock more (either way)...

**Comment by bast** [comment]
My feeling is that we are using non-standard or some "undefined" CSS behavior and it gets corrected on some browser setups but not on others.
